config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :related_products
    resources :categories
    resources :products
    resources :newsletters
    resources :brands
    root to: "products#index"
  end
  root to: 'main#index'
  resources :brand, only: [:index, :show] do
    resources :product, only: [:show]
  end
  resources :category, only: [:show]
  resources :search, only: [:index]
  resource :cart, only: [:show, :destroy] do
    resources :cart_items, only: [:create, :destroy], path: 'items', as: 'items'
  end
  post 'subscribe', to: 'newsletters#create_subscribe'
  delete 'cancel_subscribe', to: 'newsletters#cancel_subscribe'
  get '/:token/confirm_email/', to: 'newsletters#confirm_email', as: 'confirm_email'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  belongs_to :user

  validates :user, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout false

  def show
  end

  def destroy
    current_cart.destroy
    render :show
  end

end

app/helpers/carts_helper.rb
module CartsHelper

  def products
    @products ||= items.joins(:product).all
  end

  def get_cart_quantity_sum(products)
    products.inject(0){ |sum, p| sum + p.quantity }
  end

  def get_cart_summary(products)
    products.inject(0){ |sum, p| sum + p.price * p.quantity }
  end
end

app/views/shared/cart/_cart.html.haml
- unless current_user.nil?
  - if !products.empty?
    .table-responsive
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th Image
            %th Product Name
            %th Quantity
            %th Price
            %th
              %span.glyphicon.glyphicon-remove{'aria-hidden': 'true'}
        %tbody
          - products.each do |item|
            %tr
              %td= get_img_or_title_link(item)
              %td= link_to item.title, brand_product_path(item.brand_id, item.product_id)
              %td= item.quantity
              %td= item.price
              %td
                %span.glyphicon.glyphicon-remove.text-danger.del-item{ 'data-id': item.product_id, 'aria-hidden': 'true' }
          %tr
            %td Quantity:
            %td.text-right.cart-qty{colspan: 4}= "#{get_cart_quantity_sum(products)}"
          %tr
            %td Summary:
            %td.text-right.cart-sum{colspan: 4}= "#{format("%.2f", get_cart_summary(products))} $"
  - else
    %h3 Cart is empty.
- else
  %span Please sign in! To view the cart
  -#FIX
  // :javascript
  //   $(document).on('turbolinks:load', function(){
  //     $('#cart .modal-footer a, #cart .modal-footer .btn-danger').css('display', 'none')
  //   });