config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :related_products
    resources :categories
    resources :products
    resources :newsletters
    resources :brands
    root to: "products#index"
  end
  root to: 'main#index'
  resources :brand, only: [:index, :show] do
    resources :product, only: [:show]
  end
  resources :category, only: [:show]
  resources :search, only: [:index]
  resource :cart, only: [:show, :destroy] do
    resources :cart_items, only: [:create, :destroy], path: 'items', as: 'items'
  end
  post 'subscribe', to: 'newsletters#create_subscribe'
  delete 'cancel_subscribe', to: 'newsletters#cancel_subscribe'
  get '/:token/confirm_email/', to: 'newsletters#confirm_email', as: 'confirm_email'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
  has_one_attached :img

  validates :title, presence: true
  validates :description, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  belongs_to :user

  validates :user, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :product,  presence: true
  validates :cart,     presence: true
  validates :quantity, presence: true, numericality: { only_integer: true  }

  delegate :title, :imgs, :price, :brand_id, to: :product

end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true

  scope :parent_root, -> { where(ancestry: nil) }
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord

  validates :email, presence: true, uniqueness: true
  
end

app/models/product.rb
require 'elasticsearch/model'
class Product < ApplicationRecord
  include ActiveModel::Validations

  has_many :related_products, dependent: :destroy
  has_many :related, through: :related_products
  belongs_to :category
  belongs_to :brand

  has_many_attached :imgs
  enum status: { active: 'active', nonactive: 'nonactive'}, _suffix: true

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :title, presence: true
  validates :description, presence: true
  validates :status, inclusion: { in: Product.statuses }

  scope :hits, -> { where(hit: true) }
  scope :recent, -> (viewed_products) { where(id: viewed_products) }

  def as_indexed_json(options = {})
    self.as_json(
      only: [:id, :title, :description],
      include: {
        brand: {
          only: [:title]
        }
      }
    )
  end
end

app/models/related_product.rb
class RelatedProduct < ApplicationRecord
  belongs_to :related, class_name: 'Product'
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy
  has_many :products, through: :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_cart
    @current_cart ||= begin
      Cart.find_or_create_by(user: current_user)
    end
  end

  def items
    current_cart.cart_items
  end

  helper_method :current_cart, :items
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  layout false

  def create
    current_cart.cart_items.create(cart_items_params)
  end

  def destroy
    current_cart.cart_items.find_by(cart_items_params).destroy
    render :create
  end

  private

  def cart_items_params
    params.require(:cart_item).permit(:quantity, :product_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout false

  def show
  end

  def destroy
    current_cart.destroy
    render :show
  end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :set_category, only: [:show]

  def show
    set_page_options
  end

  private

  def set_category
    @category = Category.includes(:products).find(params[:id])
    @category_products = @category.products
  end

  def set_page_options
    add_breadcrumb 'Home', root_path, title: 'Home'
  end

  def category_params
    params.require(:category).permit()
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @brands = Brand.limit(3)
    @hits = Product.hits.limit(8).with_attached_imgs
  end

end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController

  def create_subscribe
    result = NewsletterService::Subscribe.call(Newsletter.new(newsletter_params))
    if result.success?
      flash[:success] = 'Thanks, for subscribe! Please confirm your email address'
    else
      flash[:error] = result.errors
    end
    redirect_to root_path
  end

  def cancel_subscribe
  end

  def confirm_email
    result = NewsletterService::ConfirmEmail.call(params[:token])
    if result.success?
      flash[:success] = "You successfuly confirmed email!"
    else
      flash[:error] = result.errors
    end
    redirect_to root_path
  end
  private

  def newsletter_params
    params.fetch(:newsletter, {}).permit(:email)
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :set_product, only: [:show]
  after_action :register_visit_to_session, only: [:show]

  def show
    set_page_options
  end

  private

  def set_page_options
    add_breadcrumb 'Home', root_path, title: 'Home'
  end

  def register_visit_to_session
    session[:viewed_products] ||= []
    session[:viewed_products] = (session[:viewed_products] + [@product.id])
                                .uniq
                                .take(3)
  end

  def set_product
    brand = Brand.find(params[:brand_id])
    @product = brand.products.find(params[:id])
    @recent_products = Product.recent(session[:viewed_products]).with_attached_imgs
  end

  def product_params
    params.require(:product).permit(:brand_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_page_options

  def index
    response = Product.__elasticsearch__.search(
      query: {
        multi_match: {
          query: params[:query],
          fields: ['title', 'description', 'brand.title']
        }
      }
    )
    @products = response.records.to_a
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def set_page_options
    add_breadcrumb 'Home', root_path, title: 'Home'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def products
    @products ||= items.joins(:product).all
  end

  def get_cart_quantity_sum(products)
    products.inject(0){ |sum, p| sum + p.quantity }
  end

  def get_cart_summary(products)
    products.inject(0){ |sum, p| sum + p.price * p.quantity }
  end
end

app/helpers/main_helper.rb
module MainHelper
  def categories
    Category.roots
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def get_img_or_title_link(cart_item)
    if cart_item.imgs.nil?
      link_to cart_item.title, brand_product_path(cart_item.brand_id, cart_item.product_id)
    else
      link_to(image_tag(cart_item.imgs.first), brand_product_path(cart_item.brand_id, cart_item.product_id))
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def get_button_title(method)
    if method == :post
      'Sign Up!'
    elsif method == :put
      'Update'
    end
  end

  def method_put?(method)
    method == :put
  end
end

app/views/cart_items/create.html.haml
= render 'shared/cart/cart'

app/views/shared/main/_account_menu.html.haml
- if user_signed_in?
  - if current_user.try(:admin)
    %li
      = link_to 'Administrator', "#", style: 'color: red'
    %li
      = link_to 'API', '/oauth/applications', style: 'color: blue'
  %li
    = link_to "Hi, #{current_user.email}", "#"
  %li
    = link_to "Logout", destroy_user_session_path, method: :delete
  %li
    = link_to 'Profile', edit_user_registration_path
- else
  %li
    = link_to 'Login', new_user_session_path
  %li
    = link_to 'Sign Up', new_user_registration_path

app/views/shared/main/_bottom_header.html.haml
.container
  .header
    .col-md-9.header-left
      .top-nav
        %ul.memenu.skyblue
          %li.active= link_to 'Home', root_path
          - categories.each do |category|
            - cache category do
              %li.grid
                = link_to category.title, category_path(category.id)
                - if category.children.present?
                  .mepanel
                    .row
                      .col1.me-one
                        = render 'shared/menu/menu', category: category, cached: true
      .clearfix
    .col-md-3.header-right
      .search-bar
        //Search
        = form_with(url: '/search', method: 'get', html: { autocomplete: 'off'}) do |f|
          = f.text_field :query, class: 'typeahead', id: 'typeahead',  placeholder: 'Search...'
          = f.submit ""
    .clearfix

app/views/shared/main/_footer.html.haml
.information
  .container
    .infor-top
      .col-md-3.infor-left
        %h3 Follow Us
        %ul
          %li
            %a{href: "#"}
              %span.fb
              %h6 Facebook
          %li
            %a{href: "#"}
              %span.twit
              %h6 Twitter
          %li
            %a{href: "#"}
              %span.google
              %h6 Google
      .col-md-3.infor-left
        %h3 Information
        %ul
          %li=link_to "<p>Specials</p>".html_safe, "#"
          %li=link_to "<p>New Products</p>".html_safe, "#"
          %li=link_to "<p>Our Stores</p>".html_safe, "#"
          %li=link_to "<p>Contact Us</p>".html_safe, "#"
          %li=link_to "<p>Top Sellers</p>".html_safe, "#"
      .col-md-3.infor-left
        %h3 My Account
        %ul
          %li=link_to "<p>My Account</p>".html_safe, "#"
          %li=link_to "<p>My credit slips</p>".html_safe, "#"
          %li=link_to "<p>My Merchandise returns</p>".html_safe, "#"
          %li=link_to "<p>My Personal Info</p>".html_safe, "#"
          %li=link_to "<p>My addresses</p>".html_safe, "#"
      .col-md-3.infor-left
        %h3 Store information
        %h4 The company name,
          %span Lorem ipsum dolor
          Glasglow Dr 40 Fe 72,
        %h5 +955 123 4567
        %p=mail_to "contact@example.com"
      .clearfix
.footer
  .container
    .footer-top
      .col-md-6.footer-left
        = form_with(model: Newsletter.new, url: subscribe_path) do |f|
          = f.text_field :email, {placeholder: 'Enter Your Email', required: true}
          = f.submit 'Subscribe!'
.modal.fade#cart{'tabindex': '-1', role: 'dialog', 'aria-label': 'myModalLabel'}
  .modal-dialog.modal-lg{role: 'document'}
    .modal-content
      .modal-header
        %button{class: 'close', 'data-dismiss': 'modal', 'arial-label': 'Close'}
          %span{'aria-hidden': true}
        %h4.modal-title#myModalLabel Cart
      .modal-body
      .modal-footer
        %button{class: 'btn btn-default', 'data-dismiss': 'modal'} Continue shopping
        %a{href: 'cart/index', type: 'button', class: 'btn btn-primary'} Order
        %button{class: 'btn btn-danger clearCart'} Clear cart

app/views/shared/main/_top_header.html.haml
.top-header
  .container
    .top-header-main
      .col-md-6.top-header-left
        .drop
          .box
            = select :currencies, :currency, ['Euro', 'Dollar'], {selected: 'Euro'}, {tabindex: '4', class: 'dropdown'}
          .box1
            = select :languages, :language, ['English', 'Polish'], {selected: 'English'}, {tabindex: '4', class: 'dropdown'}
          .btn-group
            %a{class: 'dropdown-toggle', 'data-toggle': 'dropdown'}
              Account
              %span.caret
            %ul.dropdown-menu
              = render 'shared/main/account_menu'
          .clearfix
      .col-md-6.top-header-left
        .cart.box_1
          %a{href: cart_path, remote: true, class: 'cart-link'}
            .total
              = image_tag 'cart-1.png'
              - if items.any?
                %span.simpleCart_total
                  = "#{format("%.2f", get_cart_summary(items))} $"
              - else
                %span.simpleCart_total Empty Cart
          .clearfix
      .clearfix